docs: Update README
Doro-Group/git-it pull request #3
Opened 2021-01-28 14:07 UTC by pettax

2021-01-28 14:09 UTC, axelolsson requested changes

2021-01-28 14:09 UTC, axelolsson commented on README.md
> +## To install the tools
Actually they are all present in the `package.json` and the configuration-file already lives in the root so all you need to do is `npm install`.

2021-01-29 07:19 UTC, axelolsson reviewed
All commits should follow convention! There is no exception. :)

2021-01-29 08:22 UTC, pettax commented
> All commits should follow convention! There is no exception. :)

Even if they are local to a PR (short-lived branch) and about to get squashed?

2021-01-29 08:51 UTC, axelolsson commented
> > All commits should follow convention! There is no exception. :)
> 
> Even if they are local to a PR (short-lived branch) and about to get squashed?

Even then yes :)

2021-01-29 15:34 UTC, merged